### ISSUE TITLE
How long will it take to train a large scRNA-seq dataset

### ISSUE THREAD

**Issue by TerminatorJ** [imsb-uke/scGAN#18]
Dear author, I have a large scRNA-seq dataset, but indeed less than I million shown on your paper.
I'am eager to know how long will it take for I million cells?
For me, I have a dataset with 20.000 cells and 50000 genes, it takes a long while to train the model (more than 10 hours, and still running now).
Do you have any suggestions to cut the time for training my data?
Thank you so much!!!

**Comment by pierremac** [comment]
It's basically impossible to predict how long one training experiment will take as it depends on too many factors.
The most important factor is probably the hardware you are using.
Are you training on a GPU? What model?
If you are running on CPU, it's not impossible but training will likely take days.
If you want to reduce the training time, the most obvious thing you can do is to reduce the number of training steps (defined in the parameters.json file). The training time should be roughly proportional to that number.
