### ISSUE TITLE
about evaluation indicators

### ISSUE THREAD

**Issue by kingkingofall** [imsb-uke/scGAN#22]
I am very interested in this work and want to know about the evaluation indicators of model generation. I saw that a randomforest classifier is used in the paper to classify real samples and generated samples.Is this step directly training model with generated samples and real samples?I want to know more about the details of the evaluation indicators?

**Comment by fhausmann** [comment]
Hello @kingkingofall,

Please have a look in the [paper](https://www.nature.com/articles/s41467-019-14018-z#Sec10), especially section "Classification of real versus generated cells". 
The training of the random forest classifier was directly trained on real test samples and generated cells. 
Other details for the evaluation metrics are explained in the paper as well.

Please let me know if you have any additional questions!
