### ISSUE TITLE
Missing var names in cscGAN

### ISSUE THREAD

**Issue by ubioinformat** [imsb-uke/scGAN#8]
Hi! 

After running the cscGAN I have noticed that the outputted generated cells have no gene names. As some genes were dropped in the preprocessing there is a length mismatch among the input and output genes, is there a way to know which genes have been dropped? 

Maybe here the gene names can be added as .var_names? 

![image](https://user-images.githubusercontent.com/65729110/139088236-10aaf064-fe86-42ea-8c95-1cbeabb867f2.png)

Thanks in advance!

Jesús.

**Comment by RaphaelTEBOUL** [comment]
Hi, 

You actually have access to the proper gene names if you have a look at the ./experiments/YOUR_EXPERIMENT/YOUR_EXPERIMENT.h5ad created ! 

Best, 

Raphaël

**Comment by fhausmann** [comment]
Dear @ubioinformat, 
Sorry for the late reply.
Did the information from @RaphaelTEBOUL, fixed your issue? 
If not, I'll have a look into it. 

Best, 
Fabian

**Comment by ubioinformat** [comment]
Yes it worked! 

Sorry for the late reply. Thank you all!
