### ISSUE TITLE
Dockerfile needed modification to build

### ISSUE THREAD

**Issue by AJnsm** [imsb-uke/scGAN#9]
After copying the requirements.txt file into the dockerfile directory, I ran 

`docker build -t scgan_container ./dockerfile`

Expected behaviour: container image gets built. 

Observed behaviour:
Got the  error 
`CMake Error: Unknown argument --`

And no container gets built. 

The readme mentions that it needs cmake 3.18.2. I changed line  13 of the Dockerfile to:

`RUN pip3 install cmake==3.18.2 && \`

and now the container gets built.

**Comment by AJnsm** [comment]
Ok this builds the container, but with python3.5. You can add python3.6, which is listed as a requirement, with 

````
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update \
  && apt-get -y --no-install-recommends install ssh python3.6-tk python3-pip  libxml2-dev libhdf5-dev llvm \
  && pip3 install --upgrade 'pip<21' setuptools wheel
````

But this still installs the dependencies only for python3.5. Any suggestions?

**Comment by fhausmann** [comment]
Hello,
scGAN should work with Python 3.5 as well, so there should be no need for installing python 3.6.
I hope that solves the issue after you fixed the cmake issue. 
However, I'll have a look into it and will provide a working dockerfile soon.    

Best,
Fabian
